### PR TITLE
Fixing the Dynamo v1 Schema implicit conversions and adding new v2 conversions

### PR DESCRIPTION
**Pull request by glidester**
Hi @mingchuno, hopefully this pull request will be to your fork this time. 

Here are the changes we discussed.

I've created a new set of implicit conversion functions for the DynamoDb v2 schema in com.github.dwhjames.awswrap.dynamodb.v2.DataTypeConversions

I abstracted out the common code from com.github.dwhjames.awswrap.package into the new com.github.dwhjames.awswrap.dynamodb.QueryBuilder trait.

There is also now a comprehensive suite of integration test for the different combinations of data types and collections for both v1 and v2 schema code (although I think my DataTypeConversionSpec is broken in all but my very last commit sorry).

While writing the tests for the existing v1 code I noticed two errors that were introduced from previously pulled-in commits to your fork. I've completed the change started by one of them and completely reversed out the other (please read my commit comments for more detailed explanations).

I hope these changes are ok, please let me know if you have any questions or suggestions.

Cheers,

Tim

### CODE REVIEW

**Comment by mingchuno** [comment]
@glidester I saw CI failing?

**Comment by glidester** [comment]
Yes I only just saw it this morning sorry. 

First issue (now fixed by removing it) was that I'd left in a unit test from janlisse (and I reversed out his changes so his test was now failing). I've only been running the `it:test` on my box so I didn't pick it up before committing.

The current issue only effects compiling against Scala 2.10.5 (I'm using 2.11.8 on my dev box). I'm still investigating but the issue is caused by the compiler options `-Ywarn-numeric-widen` and `-Xfatal-warnings`.

Looks like [this forum post](https://groups.google.com/forum/#!topic/scala-internals/Gi-54GeWv-M%5B26-50%5D) discusses the issue but I'm still reading through it.

I've also found [this bug](https://issues.scala-lang.org/browse/SI-8340)

Not sure what the solution is at this point. As it only affects the old 2.10.X scala perhaps we could disable the `-Ywarn-numeric-widen` flag when compiling for 2.10.X (is that possible with sbt?).

Tim

**Comment by glidester** [comment]
Ok, I've figured out how to selectively remove the `-Ywarn-numeric-widen` for just 2.10.

Would this be an acceptable solution? Let me know and if so and I'll commit my workaround.

**Comment by mingchuno** [comment]
@glidester Yes, go ahead. Thank you very much

**Comment by mingchuno** [comment]
@glidester Finally got time to review your work. Thank you very much for your work. Excellent job! Especially on the details test suit. I've just got 1 quick question before accepting the PR and release a new version: Will the changes break the compatibility of existing clients?

**Comment by glidester** [comment]
I believe it will only affect a very small set of code bases.

It will only break code that relied upon this recent commit: [ba4350](https://github.com/glidester/aws-wrap/commit/ba43507833a2e0e4727befc3cc3b8b4f5d7585a5) that you merged at the end of last year. All older code will be unaffected.  

That commit half added the Dynamo v2 schema `getBOOL` method to the original implicit conversions. 

These I think we have agreed should remain using the v1 schema data types. 

Those affected should be able to just switch to the new v2 implicit conversions (but obviously I can't be certain about this).

**Comment by mingchuno** [comment]
@glidester Thank you for your prompt reply. I will merge your PR and publish a new version. You can test around when new version release.

**Pull request merged**
