### PR TITLE
Adds Kinesis and Firehose support

### PR DESCRIPTION
**Pull request by etspaceman**

### CODE REVIEW

**Comment by etspaceman** [comment]
@mingchuno cleaned up and created a new PR

**Comment by etspaceman** [comment]
@mingchuno how's this look? any further tweaks needed?

**Comment by mingchuno** [comment]
@etspaceman look nice, I will merge now and publish new version later

**Comment by etspaceman** [comment]
Thanks @mingchuno. When do you plan to publish? I'd like to make use of this in my library.

**Comment by mingchuno** [comment]
@etspaceman It has been published

**Pull request merged**
