### PR TITLE
Kinesis and Firehose Support

### PR DESCRIPTION
**Pull request by etspaceman**
@mingchuno I added some Kinesis/Firehose support w/ this PR. Let me know what you think.

### CODE REVIEW

**Comment by mingchuno** [comment]
Can we have some sort of test? (If not possible, that's ok)

**Comment by etspaceman** [comment]
@mingchuno we can but the only way I see to get some sort of local Kinesis instance for the integration tests is to use https://github.com/mhart/kinesalite - a NodeJS app distributed via NPM.  The travis build would need to be modified to include NPM in some way. 

Do you have a good way of approaching this? If so, I can include some sort of integration test.

**Comment by etspaceman** [comment]
@mingchuno  nevermind - got the integration test figured out.

**Comment by mingchuno** [comment]
@etspaceman Can you do a rebase and tidy up the commit?

**Comment by etspaceman** [comment]
I can tomorrow. Another option is to use squash and merge so your master branch is a clean, single commit.

**Comment by mingchuno** [comment]
@etspaceman Thank you very much. Yes, I am aware of the "squash and merge" in GitHub. But what I want is to squash into a few commits that are easier to follow.

**Comment by etspaceman** [comment]
Closed for new, cleaner PR

**Pull request closed without merging**
